### ISSUE TITLE
Need another color for the links

### ISSUE THREAD

**Issue by trmdi** [Takemikazuchi00/KvIce#1]
The blur text on the black background is too difficult to see.

![image](https://user-images.githubusercontent.com/11857205/45401831-b396bb00-b67c-11e8-8c24-0b2a14d8f9ea.png)

**Comment by Takemikazuchi00** [comment]
Thanks for the feedback
![screenshot_download new icon themes_20180914_004043](https://user-images.githubusercontent.com/33161548/45505839-da0d4100-b7b7-11e8-9c5a-6e2e558a86c4.png)

**Comment by trmdi** [comment]
https://github.com/Takemikazuchi00/KvIce/commit/e206e7a4436cf5a78ec28dd48d696d6b37883ada
